name: PR
on: [pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm audit --audit-level=high

  build-deps:
    uses: ./.github/workflows/build-deps.yml
    secrets:
      SIC_PAT: ${{ secrets.SIC_PAT }}
      VITE_ENCRYPTION_KEY: ${{ secrets.VITE_ENCRYPTION_KEY }}

  build-linux:
    needs: build-deps
    uses: ./.github/workflows/build-linux.yml
    secrets:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}

  build-windows:
    needs: build-deps
    uses: ./.github/workflows/build-windows.yml
    secrets:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}

  build-macos:
    needs: build-deps
    uses: ./.github/workflows/build-macos.yml
    secrets:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
