name: Build macOS

on:
  workflow_call:
    secrets:
      VITE_SENTRY_DSN:
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Download built deps
        uses: actions/download-artifact@v6
        with:
          name: built-deps
          path: built-deps/

      - name: Copy deps into src
        run: cp -r built-deps/* src/

      - name: ClamAV scan
        run: |
          brew install clamav > /dev/null
          sudo mkdir -p /usr/local/etc/clamav
          sudo cp /opt/homebrew/etc/clamav/freshclam.conf.sample /opt/homebrew/etc/clamav/freshclam.conf
          sudo sed -i '' 's/^Example/#Example/' /opt/homebrew/etc/clamav/freshclam.conf
          freshclam --quiet
          clamscan --recursive --infected --alert-broken src/ node_modules/

      - name: Build electron
        run: npm run make
